[Log]
Level = 'warn'

[WebServer]
AllowOrigins = '*'
SecureCookies = false

[WebServer.TLS]
HTTPSPort = 0

[[EVM]]
ChainID = '1'

[[EVM.Nodes]]
Name = 'Sepolia'
WSURL = 'wss://geth'
HTTPURL = 'https://geth'
