# TODO: Pass in required secrets for Chainlink container safely
---
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: high-priority-nonpreempting
value: 1000000
preemptionPolicy: Never
globalDefault: false
description: "This priority class will not cause other pods to be preempted."
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-lens-api-ea-access
spec:
  podSelector:
    matchLabels:
      app: lens-api-ea
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: chainlink-node
    ports:
    - protocol: TCP
      port: 8080
# --- 
# apiVersion: v1
# kind: Secret
# metadata:
#   name: chainlink-secrets-toml
#   #namespace: socialmaven
# type: Opaque
# stringData:
#   secrets.toml: |
#     [Password]
#     Keystore = 'POSTGR3S123456789!'
#     [Database]
#     URL = 'postgresql://postgres:POSTGR3S123456789!<rds>:5432/chainlink_db'
# ---
# apiVersion: v1
# kind: Secret
# metadata:
#   name: chainlink-configmap
#   #namespace: socialmaven
# type: Opaque
# stringData:
#   API_LOGIN: |
#     x@y.z
#     POSTGR3S123456789!
# ---
# apiVersion: v1
# kind: Secret
# metadata:
#   name: lens-ea-env
#   #namespace: socialmaven
# type: Opaque
# stringData:
#   API_LOGIN: |
#     x@y.z
#     POSTGR3S123456789!
# ---
# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: chainlink-config-toml
#   #namespace: socialmaven
# data:
#   config.toml: |
#     [Log]
#     Level = 'warn'

#     [WebServer]
#     AllowOrigins = '*'
#     SecureCookies = false

#     [WebServer.TLS]
#     HTTPSPort = 0

#     [[EVM]]
#     ChainID = '80001'

#     [[EVM.Nodes]]
#     Name = 'Mumbai'
#     WSURL = 'wss://geth:8546'
#     HTTPURL = 'https://geth:8545'
# ---
# apiVersion: v1
# kind: Pod
# metadata:
#   name: chainlink
#   #namespace: socialmaven
# spec:
#   containers:
#   - name: chainlink
#     image: smartcontract/chainlink:2.0.0
#     imagePullPolicy: IfNotPresent
#     priorityClassName: high-priority
#     # resources:
#     #   requests:
#     #     memory: 64Mi
#     #     cpu: 500m
#       # limits:
#       #   memory: 128Mi
#       #   cpu: 5000m
#     ports:
#     - containerPort: 6688
#       name: chainlink
#     command: ["chainlink", "node"]
#     args: ["-config", "/etc/chainlink/config/config.toml", "-secrets", "/etc/chainlink/secrets/secrets.toml", "start", "-api", "/etc/chainlink/api"]
#     volumeMounts:
#     - name: config
#       mountPath: /etc/chainlink
#     - name: config-toml
#       mountPath: /etc/chainlink/config
#     - name: secrets-toml
#       mountPath: /etc/chainlink/secrets
#   # - name: postgres
#   #   image: postgres:latest
#   #   ports: 
#   #   - containerPort: 5432 
#   #     name: postgresql
#   #   env:
#   #   - name: POSTGRES_USER
#   #     value: postgres
#   #   - name: POSTGRES_DB
#   #     value: chainlink_db
#   #   - name: POSTGRES_PASSWORD
#   #     value: POSTGR3S123456789!
#   tolerations:
#   - key: ""
#     operator: "Exists"
#   volumes:
#   - name: config
#     secret:
#       secretName: chainlink-configmap
#       items:
#       - key: API_LOGIN
#         path: api
#   - name: config-toml
#     configMap:
#       name: chainlink-config-toml
#       items:
#       - key: config.toml
#         path: config.toml
#   - name: secrets-toml
#     secret:
#       secretName: chainlink-secrets-toml
#       items:
#       - key: secrets.toml
#         path: secrets.toml
