apiVersion: v1
kind: Pod
metadata:
  name: chainlink-ea
  #namespace: socialmaven
spec:
  containers:
  - name: chainlink
    image: smartcontract/chainlink:2.0.0 # TODO: Update to Lens EA 
    imagePullPolicy: IfNotPresent
    ports:
    - containerPort: 8080
      name: chainlink-ea
    command: ["yarn", "start"]
    volumeMounts:
    - name: config
      mountPath: /etc/chainlink
    - name: config-toml
      mountPath: /etc/chainlink/config
    - name: secrets-toml
      mountPath: /etc/chainlink/secrets
  volumes:
  - name: config
    configMap:
      name: chainlink-configmap
      items:
      - key: API_LOGIN
        path: api
  - name: config-toml
    configMap:
      name: chainlink-config-toml
      items:
      - key: config.toml
        path: config.toml
  - name: secrets-toml
    secret:
      secretName: chainlink-secrets-toml
      items:
      - key: secrets.toml
        path: secrets.toml
