# https://docs.chain.link/chainlink-nodes/v1/running-a-chainlink-node
# TODO: Pass in required secrets for Chainlink container safely

---
apiVersion: v1
kind: Secret
metadata:
  name: chainlink-secrets-toml
  namespace: socialmaven
type: Opaque
stringData:
  secrets.toml: |
    [Password]
    Keystore = 'POSTGR3S123456789!'
    [Database]
    URL = 'postgresql://postgres:POSTGR3S123456789!@localhost:5432/chainlink_db?sslmode=disable'
---
apiVersion: v1
kind: Secret
metadata:
  name: chainlink-configmap
  namespace: socialmaven
type: Opaque
stringData:
  #ROOT: /chainlink
  API_LOGIN: |
    x@y.z
    POSTGR3S123456789!

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: chainlink-config-toml
  namespace: socialmaven
data:
  config.toml: |
    [Log]
    Level = 'warn'

    [WebServer]
    AllowOrigins = '*'
    SecureCookies = false

    [WebServer.TLS]
    HTTPSPort = 0

    [[EVM]]
    ChainID = '1'

    [[EVM.Nodes]]
    Name = 'Sepolia'
    WSURL = 'wss://geth:8546'
    HTTPURL = 'https://geth:8545'


---
apiVersion: v1
kind: Pod
metadata:
  name: chainlink
  namespace: socialmaven
spec:
  #restartPolicy: Never
  containers:
  - name: chainlink
    image: smartcontract/chainlink:2.0.0
    imagePullPolicy: IfNotPresent
    ports:
    - containerPort: 6688
      name: chainlink
    # command: ["/bin/sh"]
    # args: ["-c", "for i in $(seq 1 10); do echo 'Alive!'; sleep 1000; done"]
    command: ["chainlink", "node"]
    args: ["-config", "/etc/chainlink/config/config.toml", "-secrets", "/etc/chainlink/secrets/secrets.toml", "start"]
    volumeMounts:
    - name: config
      mountPath: /etc/chainlink
    - name: config-toml
      mountPath: /etc/chainlink/config
    - name: secrets-toml
      mountPath: /etc/chainlink/secrets

  - name: postgres
    image: postgres:latest
    ports: 
    - containerPort: 5432 
      name: postgresql
    env:
    - name: POSTGRES_USER
      value: postgres
    - name: POSTGRES_DB
      value: chainlink_db
    - name: POSTGRES_PASSWORD
      value: POSTGR3S123456789!

  volumes:
  - name: config
    configMap:
      name: chainlink-configmap
      items:
      - key: API_LOGIN
        path: api
  - name: config-toml
    configMap:
      name: chainlink-config-toml
      items:
      - key: config.toml
        path: config.toml
  - name: secrets-toml
    secret:
      secretName: chainlink-secrets-toml
      items:
      - key: secrets.toml
        path: secrets.toml
