apiVersion: v1
kind: Pod
metadata:
  name: geth
  namespace: socialmaven
spec:
  containers:
  - name: geth
    image: ethereum/client-go:stable
    ports:
    - containerPort: 30303
      name: p2p
    - containerPort: 8545
      name: httprpc
    - containerPort: 8546
      name: wsrpc